services:

  #Contenedor que ejecuta a MySQL
  mysql:
    image: mysql:8.4.11

    # Nombre que veremos dentro de Docker Desktop
    container_name: team-task-mysql

    #Si MySQL se cae, Docker intenta volver a levantarlo.
    restart: unless-stopped

    # Variables que utiliza la imagen oficial de MySQL
    # durante la inicializacion de la base
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    # Puerto del PC : puerto dentro del contenedor
    # Desde windows: localhost:3307
    # Dentro de Docker: mysql:3306
    ports:
      - "3307:3306"

    # Evita perder los datos cuando eliminamo/recreamo el contenedor.
    volumes:
      - mysql_data:/var/lib/mysql

    # Docker comprueba que MySQL esté listo antes de iniciar servicios que dependan de él.
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  # Contenedor donde ejecutamos nuestra API de NestJS
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: team-task-api

    command: npm run start:dev

    # localhost:3000 de windows apunta al puerto 3000 del contenedor.
    ports:
      - "3000:3000"

    #Carga las variables definidas en .env
    env_file:
      - .env

    # Montamos el código del PC dentro del contenedor.
    # Así start:dev detecta nuestros cambios.
    volumes:
      - .:/app

      # Evita reemplazar node_modules del contenedor con el del sistema del anfitrion.
      - /app/node_modules

    # La API solamente inicia después de que MySQL este saludable.
    depends_on:
      mysql:
        condition: service_healthy

# Volumen persistente utilizado por MySQL.
volumes:
  mysql_data: